import type { ExecutiveDiscoveryApiRequest } from "../contracts/ExecutiveDiscoveryApiRequest";
import type { ExecutiveDiagnosis, ExecutiveConfidence } from "../contracts/ExecutiveDiagnosis";
import { isExecutiveDiagnosisForRequest } from "../adapter/validation";

type Guard<T> = (value: unknown) => value is T;
type Shape = Record<string, Guard<unknown>>;
type Decoded<S extends Shape> = { [K in keyof S]: S[K] extends Guard<infer T> ? T : never };
function record(value: unknown): value is Record<string, unknown> { if (value === null || typeof value !== "object" || Array.isArray(value)) return false; const prototype = Object.getPrototypeOf(value); return (prototype === Object.prototype || prototype === null) && Reflect.ownKeys(value).every(key => { const descriptor = Object.getOwnPropertyDescriptor(value, key); return typeof key === "string" && !["__proto__", "constructor", "prototype"].includes(key) && !!descriptor?.enumerable && Object.prototype.hasOwnProperty.call(descriptor, "value"); }); }
function object<S extends Shape>(shape: S): Guard<Decoded<S>> { return (value): value is Decoded<S> => record(value) && Object.keys(value).every(key => Object.prototype.hasOwnProperty.call(shape, key)) && Object.keys(shape).every(key => shape[key](value[key])); }
function optional<T>(guard: Guard<T>): Guard<T | undefined> { return (value): value is T | undefined => value === undefined || guard(value); }
function list<T>(guard: Guard<T>): Guard<T[]> { return (value): value is T[] => Array.isArray(value) && Object.getPrototypeOf(value) === Array.prototype && value.length <= 1_000 && Reflect.ownKeys(value).length === value.length + 1 && Array.from({ length: value.length }, (_, index) => Object.getOwnPropertyDescriptor(value, String(index))).every(descriptor => !!descriptor?.enumerable && Object.prototype.hasOwnProperty.call(descriptor, "value") && guard(descriptor.value)); }
function choice<T extends string>(...values: T[]): Guard<T> { return (value): value is T => typeof value === "string" && values.some(candidate => candidate === value); }
const text: Guard<string> = (value): value is string => typeof value === "string" && value.length <= 4_096;
const nonempty: Guard<string> = (value): value is string => text(value) && value.trim().length > 0;
const finite: Guard<number> = (value): value is number => typeof value === "number" && Number.isFinite(value);
const unit: Guard<number> = (value): value is number => finite(value) && value >= 0 && value <= 1;
const score: Guard<number> = (value): value is number => finite(value) && value >= 0 && value <= 100;
const strings = list(nonempty);
const instant: Guard<string> = (value): value is string => nonempty(value) && Number.isFinite(Date.parse(value)) && new Date(value).toISOString() === value;
const findingStatus = choice("SUPPORTED_FINDING", "PARTIALLY_SUPPORTED", "REQUIRES_MORE_EVIDENCE", "CONTRADICTED", "NOT_DEFENDABLE");
function safeTree(value: unknown, seen = new Set<object>(), depth = 0): boolean { if (depth > 30) return false; if (value === undefined || value === null || typeof value === "boolean" || text(value) || finite(value)) return true; if (typeof value !== "object" || seen.has(value)) return false; seen.add(value); const valid = Array.isArray(value) ? list((child): child is unknown => safeTree(child, seen, depth + 1))(value) : record(value) && Object.values(value).every(child => safeTree(child, seen, depth + 1)); seen.delete(value); return valid; }
const confidenceShape = object({ support: unit, directness: unit, consistency: unit, coverage: unit, causalConfidence: unit, aggregate: unit });
const supportShape = object({ supportId: nonempty, evidenceRef: nonempty, correlationType: choice("DIRECT", "INFERENCE", "HYPOTHESIS", "CONTRADICTION"), weight: unit, rationale: text });
const claimShape = object({ claimId: nonempty, statement: nonempty, sourceNodes: strings, sourceRelationships: strings, evidenceSupports: list(supportShape), confidence: confidenceShape, status: findingStatus, createdAt: instant });
const chainShape = object({ chainId: nonempty, claims: list(claimShape), logicDescription: text });
const findingFields = { findingId: nonempty, statement: nonempty, type: choice("FINDING", "RISK", "OPPORTUNITY", "ROOT_CAUSE"), chain: chainShape, status: findingStatus, confidence: confidenceShape };
const findingShape = object(findingFields);
const riskShape = object({ ...findingFields, type: choice("RISK"), severity: choice("LOW", "MEDIUM", "HIGH", "CRITICAL"), impactArea: nonempty });
const opportunityShape = object({ ...findingFields, type: choice("OPPORTUNITY"), potentialValue: nonempty, effort: nonempty });
const rootCauseShape = object({ ...findingFields, type: choice("ROOT_CAUSE"), relatedFindings: strings });
const narrativeShape = object({ executiveSummary: text, currentState: text, burningIssues: text, opportunitiesForGrowth: text });
const summaryShape = object({ headline: text, keyInsights: strings, criticalRisksSummary: text });
const maturityLevel = choice("INITIAL", "EMERGING", "MANAGED", "INTEGRATED", "OPTIMIZING");
const dossierDimension = object({ dimension: nonempty, level: maturityLevel, score, evidenceRefs: strings, justification: nonempty });
const strengthShape = object({ id: nonempty, dimension: nonempty, description: nonempty, impact: choice("MODERATE", "HIGH", "CRITICAL"), supportingFindings: strings });
const weaknessShape = object({ id: nonempty, dimension: nonempty, description: nonempty, severity: choice("MODERATE", "HIGH", "CRITICAL"), relatedRisks: strings, rootCauses: strings });
const priorityFields = { id: nonempty, rank: finite, title: nonempty, description: nonempty, dimension: nonempty, addressedWeaknesses: strings, leveragedStrengths: strings, urgency: choice("IMMEDIATE", "SHORT_TERM", "MEDIUM_TERM") };
const priorityShape = object(priorityFields);
const recommendationShape = object({ id: nonempty, priorityId: nonempty, proposedAction: nonempty, expectedOutcome: nonempty, effortEstimate: choice("LOW", "MEDIUM", "HIGH"), evidenceRefs: strings });
const diagnosticAuditShape = object({ rejectedClaims: list(object({ claim: claimShape, reason: text })) });
const businessDiagnosisShape = object({ overallMaturity: maturityLevel, dimensionAssessments: list(dossierDimension), strengths: list(strengthShape), weaknesses: list(weaknessShape) });
const dossierShape = object({ dossierId: nonempty, reportRef: nonempty, timestamp: instant, diagnosticStatus: choice("VALID", "INSUFFICIENT_EVIDENCE"), blocks: strings, executiveSummary: summaryShape, businessDiagnosis: businessDiagnosisShape, priorities: list(priorityShape), recommendationCandidates: list(recommendationShape), narrative: narrativeShape, diagnosticAudit: diagnosticAuditShape });
const reportShape = object({ reportId: nonempty, timestamp: instant, overallStatus: findingStatus, findings: list(findingShape), risks: list(riskShape), opportunities: list(opportunityShape), rootCauses: list(rootCauseShape), rejectedClaims: list(claimShape), readinessGaps: strings });
const assessmentDimension = object({ dimension: nonempty, maturity: maturityLevel, score, strengths: strings, weaknesses: strings });
const constraintShape = object({ id: nonempty, type: choice("BUDGET", "RESOURCES", "TECHNICAL", "CULTURAL", "TIME", "REGULATORY", "GOVERNANCE", "OTHER"), description: nonempty, impactLevel: choice("LOW", "MEDIUM", "HIGH", "CRITICAL") });
const dependencyShape = object({ id: nonempty, sourcePriorityId: nonempty, targetPriorityId: nonempty, type: choice("BLOCKS", "REQUIRES", "ENHANCES") });
const readinessShape = object({ status: choice("READY", "NEEDS_PREPARATION", "NOT_READY"), score, criticalGaps: strings, constraints: list(constraintShape), dependencies: list(dependencyShape) });
const matrixShape = object({ overallConfidence: unit, support: unit, directness: unit, consistency: unit, coverage: unit, causalConfidence: unit, dimensionConfidence: (value: unknown): value is Record<string, number> => record(value) && Object.values(value).every(unit) });
const evidenceLinkShape = object({ sourceId: nonempty, sourceType: choice("CLAIM", "FINDING", "RISK", "OPPORTUNITY", "ROOT_CAUSE_HYPOTHESIS", "EVIDENCE", "CONTRADICTION"), targetId: nonempty, targetType: choice("CLAIM", "FINDING", "RISK", "OPPORTUNITY", "ROOT_CAUSE_HYPOTHESIS", "EVIDENCE", "CONTRADICTION"), description: optional(text) });
const assessmentAuditShape = object({ rejectedClaims: list(claimShape), diagnosticAudit: diagnosticAuditShape, limitations: strings, invalidReferences: strings, unresolvedContradictions: strings, insufficientEvidenceRefs: strings });
const assessmentShape = object({ assessmentId: nonempty, dossierRef: nonempty, reasoningReportRef: nonempty, executionId: nonempty, status: choice("COMPLETE", "COMPLETE_WITH_LIMITATIONS", "INSUFFICIENT_EVIDENCE", "CONTRADICTED", "NOT_DEFENDABLE"), maturityProfile: object({ overallMaturity: maturityLevel, dimensions: list(assessmentDimension) }), findings: list(findingShape), risks: list(riskShape), opportunities: list(opportunityShape), rootCauses: list(rootCauseShape), transformationPriorities: list(object({ ...priorityFields, readinessDependencyIds: strings })), recommendationCandidates: list(recommendationShape), transformationReadiness: readinessShape, confidenceMatrix: matrixShape, evidenceMap: object({ mapId: nonempty, links: list(evidenceLinkShape) }), executiveInsight: object({ summary: summaryShape, narrative: narrativeShape, keyTakeaways: list(object({ text: nonempty, sourceRefs: strings })) }), audit: assessmentAuditShape, metadata: object({ version: nonempty, schema: nonempty, generator: nonempty, policyVersion: nonempty, timestamp: instant }) });
const aggregateKeys = ["sessionId", "executionKey", "executionScenario", "targetScenario", "objectiveIds", "metadata", "extractionResult", "mentalModel", "knowledgeGraph", "evidence", "hypotheses", "coverageReport", "readinessAssessment", "planningResult", "questionHistory", "reasoningReport", "dossier", "assessment", "constraints", "transformationConstraints", "transformationDependencies", "executiveObjectives"];
const stageKeys = ["stage", "status", "executionOrigin", "admissionReference", "startedAt", "completedAt", "durationMs", "output", "errors", "warnings", "skippedReason", "metadata"];
const stageIds = ["EVIDENCE_EXTRACTION", "MENTAL_MODEL", "KNOWLEDGE_GRAPH", "KNOWLEDGE_COVERAGE", "ADAPTIVE_PLANNING", "EXECUTIVE_REASONING", "EXECUTIVE_DOSSIER", "TRANSFORMATION_ASSESSMENT"];
function fail(): never { throw new Error("EXECUTIVE_OUTPUT_INVALID"); }
function closed(value: unknown, keys: readonly string[]): Record<string, unknown> { if (!record(value) || Object.keys(value).some(key => !keys.includes(key))) return fail(); return value; }
function checked<T>(value: unknown, guard: Guard<T>): T { if (!guard(value)) return fail(); return value; }
function unique<T>(values: readonly T[], key: (value: T) => string): T[] { const result = new Map<string, T>(); for (const value of values) { const previous = result.get(key(value)); if (previous !== undefined && JSON.stringify(previous) !== JSON.stringify(value)) fail(); result.set(key(value), value); } return [...result.values()]; }
function confidence(value: number, evidenceIds: readonly string[], missing: number, basis: string): ExecutiveConfidence { return { level: value >= 0.9 ? "VERY_HIGH" : value >= 0.75 ? "HIGH" : value >= 0.5 ? "MEDIUM" : "LOW", score: value, basis: [basis], evidenceCount: new Set(evidenceIds).size, missingEvidenceCount: missing, calibrationVersion: "executive-output-projection-v1" }; }
export function mapInternalExecutionResultToExecutiveDiagnosisV1(input: unknown, request: ExecutiveDiscoveryApiRequest, expectedSessionId: string): ExecutiveDiagnosis {
  const result = closed(input, ["executionId", "sessionId", "status", "stageResults", "rawData", "errors", "warnings"]);
  if (!nonempty(result.executionId) || result.sessionId !== expectedSessionId || !["SUCCEEDED", "PARTIAL"].includes(String(result.status))) fail();
  if (!optional(list(object({ message: text, code: optional(text) })))(result.errors) || !optional(strings)(result.warnings) || (Array.isArray(result.errors) && result.errors.length > 0)) fail();
  const stages = closed(result.stageResults, stageIds);
  for (const [id, candidate] of Object.entries(stages)) { const stage = closed(candidate, stageKeys); if (stage.stage !== id || !choice("PENDING", "RUNNING", "SUCCEEDED", "PARTIAL", "FAILED", "SKIPPED", "CANCELLED", "TIMED_OUT")(stage.status) || !instant(stage.startedAt) || !instant(stage.completedAt) || !finite(stage.durationMs) || stage.durationMs < 0 || !Array.isArray(stage.errors) || !strings(stage.warnings) || !optional(choice("CURRENT_EXECUTION", "PRECOMPUTED"))(stage.executionOrigin)) fail(); }
  const selected = closed(stages.TRANSFORMATION_ASSESSMENT, stageKeys); if (selected.status !== "SUCCEEDED" || !Array.isArray(selected.errors) || selected.errors.length !== 0) fail();
  const state = closed(selected.output, aggregateKeys);
  if (state.sessionId !== expectedSessionId || !safeTree(state)) fail();
  const assessment = checked(state.assessment, assessmentShape);
  const dossier = checked(state.dossier, dossierShape);
  const reasoning = checked(state.reasoningReport, reportShape);
  if (assessment.executionId !== result.executionId || assessment.dossierRef !== dossier.dossierId || assessment.reasoningReportRef !== reasoning.reportId || dossier.reportRef !== reasoning.reportId || dossier.diagnosticStatus !== "VALID" || !["COMPLETE", "COMPLETE_WITH_LIMITATIONS"].includes(assessment.status)) fail();
  if (assessment.maturityProfile.dimensions.length === 0 || assessment.maturityProfile.overallMaturity !== dossier.businessDiagnosis.overallMaturity || assessment.audit.invalidReferences.length > 0 || assessment.audit.unresolvedContradictions.length > 0) fail();
  const evidence = new Map(request.evidence.map(item => [item.evidenceId, item.evidenceId]));
  if (state.evidence !== undefined) { if (!Array.isArray(state.evidence)) fail(); for (const item of state.evidence) { if (!record(item) || !nonempty(item.evidenceId)) fail(); const matches = request.evidence.filter(candidate => candidate.sourceReference === item.source || candidate.evidenceId === item.turnId || candidate.evidenceId === item.evidenceId); if (matches.length === 1) evidence.set(item.evidenceId, matches[0].evidenceId); } }
  const conclusions = unique([...reasoning.findings, ...reasoning.risks, ...reasoning.opportunities, ...reasoning.rootCauses, ...assessment.findings, ...assessment.risks, ...assessment.opportunities, ...assessment.rootCauses], item => item.findingId);
  const byId = new Map(conclusions.map(item => [item.findingId, item]));
  function references(ids: readonly string[]): string[] { const found = new Set<string>(); for (const id of ids) { const direct = evidence.get(id); if (direct) { found.add(direct); continue; } const finding = byId.get(id); if (!finding) fail(); for (const claim of finding.chain.claims) for (const support of claim.evidenceSupports) { const mapped = evidence.get(support.evidenceRef); if (!mapped) fail(); found.add(mapped); } } if (found.size === 0) fail(); return [...found]; }
  const allEvidenceIds = [...new Set(conclusions.flatMap(item => references([item.findingId])))]; const overallConfidence = confidence(assessment.confidenceMatrix.overallConfidence, allEvidenceIds, assessment.audit.insufficientEvidenceRefs.length, "Assessment confidenceMatrix.overallConfidence");
  const dimensions = assessment.maturityProfile.dimensions.map(item => { const source = dossier.businessDiagnosis.dimensionAssessments.filter(candidate => candidate.dimension === item.dimension); if (source.length !== 1 || source[0].score !== item.score || source[0].level !== item.maturity || !unit(assessment.confidenceMatrix.dimensionConfidence[item.dimension])) fail(); const ids = references(source[0].evidenceRefs); return { dimensionId: item.dimension, name: item.dimension, score: item.score, rationale: source[0].justification, evidenceIds: ids, confidence: confidence(assessment.confidenceMatrix.dimensionConfidence[item.dimension], ids, 0, "Assessment dimensionConfidence") }; }); if (new Set(dimensions.map(item => item.dimensionId)).size !== dimensions.length) fail();
  const executiveSummary = [dossier.narrative.executiveSummary, assessment.executiveInsight.narrative.executiveSummary, [dossier.executiveSummary.headline, ...dossier.executiveSummary.keyInsights].filter(Boolean).join(" ")].find(value => value.trim().length > 0); if (!executiveSummary) fail();
  const risks: ExecutiveDiagnosis["risks"] = unique([...assessment.risks, ...reasoning.risks], item => item.findingId).map(item => { const ids = references([item.findingId]); return { riskId: item.findingId, category: item.impactArea, title: item.statement, description: item.statement, severity: item.severity, likelihood: "UNKNOWN", impact: item.impactArea, confidence: confidence(item.confidence.aggregate, ids, 0, "Reasoning confidence.aggregate"), evidenceIds: ids }; });
  const opportunities: ExecutiveDiagnosis["opportunities"] = unique([...assessment.opportunities, ...reasoning.opportunities], item => item.findingId).map(item => { const ids = references([item.findingId]); const effort = item.effort.toUpperCase(); if (!["LOW", "MEDIUM", "HIGH"].includes(effort)) fail(); return { opportunityId: item.findingId, category: "TRANSFORMATION", title: item.statement, description: item.statement, expectedValue: item.potentialValue, feasibility: assessment.transformationReadiness.score / 100, horizon: effort === "LOW" ? "NEAR_TERM" : effort === "HIGH" ? "LONG_TERM" : "MEDIUM_TERM", confidence: confidence(item.confidence.aggregate, ids, 0, "Reasoning confidence.aggregate; feasibility uses transformation readiness; horizon uses effort"), evidenceIds: ids }; });
  const priorities = new Map(dossier.priorities.map(item => [item.id, item])); for (const item of assessment.transformationPriorities) { const prior = priorities.get(item.id); if (prior && (prior.urgency !== item.urgency || prior.description !== item.description)) fail(); priorities.set(item.id, item); }
  const recommendations: ExecutiveDiagnosis["recommendations"] = unique([...assessment.recommendationCandidates, ...dossier.recommendationCandidates], item => item.id).map(item => { const priority = priorities.get(item.priorityId); if (!priority) fail(); const ids = references(item.evidenceRefs); return { recommendationId: item.id, title: item.proposedAction, description: item.proposedAction, rationale: priority.description, priority: priority.urgency === "IMMEDIATE" ? "HIGH" : priority.urgency === "SHORT_TERM" ? "MEDIUM" : "LOW", confidence: confidence(assessment.confidenceMatrix.overallConfidence, ids, 0, "Assessment confidenceMatrix.overallConfidence"), evidenceIds: ids, expectedImpact: item.expectedOutcome, timeframe: priority.urgency, linkedActionIds: [] }; });
  const inferredFacts = unique([...assessment.findings, ...reasoning.findings], item => item.findingId).map(item => ({ label: item.statement, value: item.statement, classification: "INFERRED" as const, evidenceIds: references([item.findingId]) }));
  const diagnosis: ExecutiveDiagnosis = {
    diagnosisId: assessment.assessmentId, schemaVersion: "1.0", capabilityVersion: request.capabilityVersion, organizationId: request.organizationId, tenantId: request.tenantId, companyId: request.companyId, sessionId: request.sessionId, status: assessment.status === "COMPLETE" && result.status === "SUCCEEDED" ? "COMPLETE" : "PARTIAL", executiveSummary,
    businessSnapshot: { confirmedFacts: [], inferredFacts, systemObservations: [], missingInformation: [] },
    maturity: { overallScore: dimensions.reduce((sum, item) => sum + item.score, 0) / dimensions.length, level: ({ INITIAL: "INITIAL", EMERGING: "DEVELOPING", MANAGED: "STRUCTURED", INTEGRATED: "ADVANCED", OPTIMIZING: "LEADING" } as const)[assessment.maturityProfile.overallMaturity], dimensions, rationale: `Assessment maturity profile: ${assessment.maturityProfile.overallMaturity}; score is the mean of assessed dimensions.`, evidenceIds: [...new Set(dimensions.flatMap(item => item.evidenceIds))], confidence: overallConfidence },
    risks, opportunities, recommendations, actions: [],
    confidence: overallConfidence, evidenceIds: [...new Set([...allEvidenceIds, ...dimensions.flatMap(item => item.evidenceIds), ...recommendations.flatMap(item => item.evidenceIds)])],
    warnings: ["SHADOW_ONLY", ...(opportunities.length ? ["OPPORTUNITY_FEASIBILITY_USES_READINESS", "OPPORTUNITY_HORIZON_USES_EFFORT"] : []), ...(assessment.status === "COMPLETE_WITH_LIMITATIONS" ? ["ASSESSMENT_HAS_LIMITATIONS"] : [])],
    generatedAt: assessment.metadata.timestamp,
    generationMetadata: { requestId: request.requestId, correlationId: request.correlationId, providerId: "aura-intelligence-executive-pipeline", providerVersion: "1", deterministic: true },
  };
  if (!isExecutiveDiagnosisForRequest(diagnosis, request)) fail();
  return diagnosis;
}
