import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { Firestore } from "firebase-admin/firestore";
import { LoginTicket, OAuth2Client } from "google-auth-library";
import { createExecutiveDiscoveryHttpHandlerV1 } from "../receiver/evaluateExecutiveDiscoveryV1";
import { mapInternalExecutionResultToExecutiveDiagnosisV1 } from "../receiver/mapInternalExecutionResultToExecutiveDiagnosisV1";
import { createExecutiveDiscoveryReceiverCompositionV1, EXECUTIVE_DISCOVERY_RECEIVER_AUDIENCE_V1, EXECUTIVE_DISCOVERY_MAX_BODY_BYTES_V1 } from "../../../composition/discoveryIntelligence/createExecutiveDiscoveryReceiverCompositionV1";
import { OidcServiceIdentityVerifierV1, DISCOVERY_OIDC_EXPECTED_SERVICE_ACCOUNT_EMAIL_V1 } from "../../../composition/discoveryIntelligence/OidcServiceIdentityVerifierV1";
import { FirestoreOidcServiceIdentityBindingResolverV1 } from "../../../composition/discoveryIntelligence/FirestoreOidcServiceIdentityBindingResolverV1";
import type { ExecutiveDiscoveryApiRequest } from "../contracts/ExecutiveDiscoveryApiRequest";
import { isExecutiveDiagnosisForRequest } from "../adapter/validation";

const controls = vi.hoisted(() => ({ policy: "ALLOW", dispatches: 0, queries: [] as unknown[] }));
vi.mock("../../../composition/discoveryIntelligence/createGovernedDiscoveryRuntimeCompositionV1", async importOriginal => {
  const actual = await importOriginal<typeof import("../../../composition/discoveryIntelligence/createGovernedDiscoveryRuntimeCompositionV1")>();
  return { ...actual, createGovernedDiscoveryRuntimeCompositionV1(dependencies: Parameters<typeof actual.createGovernedDiscoveryRuntimeCompositionV1>[0]) {
    return actual.createGovernedDiscoveryRuntimeCompositionV1({ ...dependencies, featurePolicyPort: { getEffectivePolicy: async () => undefined, async evaluateAuthoritativePolicy(query) {
      controls.queries.push(query);
      const base = { schemaVersion: "1" as const, authorizationPolicyVersion: "test-policy-v1", evaluatedTenantId: query.tenantId, evaluatedConsumerId: query.consumerId, evaluatedSource: query.source, evaluatedActor: query.actor, requestedMode: query.requestedMode };
      if (controls.policy === "DENY") return { ...base, decision: "DENIED" as const, reasonCode: "POLICY_DISABLED" as const };
      return { ...base, decision: "ALLOWED" as const, reasonCode: "POLICY_ALLOWED" as const, effectiveExecutionMode: controls.policy === "ESCALATE" ? "EVALUATION" as const : "SHADOW_ONLY" as const, effectiveTimeoutMs: 30_000 };
    } } });
  } };
});
const T = "2026-07-28T12:00:00.000Z";
const EARLIER = "2026-07-28T11:59:00.000Z";
function request(): ExecutiveDiscoveryApiRequest { return { schemaVersion: "1.0", capabilityVersion: "1.0.0", requestId: "business-request", correlationId: "business-correlation", idempotencyKey: "business-key", organizationId: "business-org", tenantId: "untrusted-business-tenant", companyId: "business-company", sessionId: "business-session", discoveryDefinitionVersion: "legacy-discovery-v1", locale: "es-MX", requestedAt: T, consentAssertion: { receiptId: "receipt-1", privacyConsent: true, diagnosticProcessingConsent: true, consentVersion: "1", capturedAt: T }, evidence: [{ evidenceId: "legacy-dossier.industry", fieldId: "dossier.industry", sourceType: "STRUCTURED_FIELD", sourceReference: "discovery_sessions/business-session#dossier.industry", value: "HOSPITALITY", capturedAt: T, classification: "USER_CONFIRMED", consentScope: "executive-diagnosis", confidence: 1 }], metadata: { evaluationMode: "SHADOW" } }; }
function output(sessionId = "trusted-correlation") {
  const confidence = { support: 0.8, directness: 0.8, consistency: 0.8, coverage: 0.8, causalConfidence: 0.8, aggregate: 0.8 };
  const claim = { claimId: "claim-1", statement: "Scheduling controls are established.", sourceNodes: [], sourceRelationships: [], evidenceSupports: [{ supportId: "support-1", evidenceRef: "legacy-dossier.industry", correlationType: "DIRECT", weight: 1, rationale: "Confirmed discovery evidence." }], confidence, status: "SUPPORTED_FINDING", createdAt: T };
  const finding = { findingId: "finding-1", statement: "Scheduling controls are established.", type: "FINDING", chain: { chainId: "chain-1", claims: [claim], logicDescription: "Evidence supports the finding." }, status: "SUPPORTED_FINDING", confidence };
  const risk = { ...finding, findingId: "risk-1", type: "RISK", statement: "Manual reconciliation can delay payroll.", severity: "HIGH", impactArea: "Payroll" };
  const opportunity = { ...finding, findingId: "opportunity-1", type: "OPPORTUNITY", statement: "Automate payroll reconciliation.", potentialValue: "Reduce reconciliation delays.", effort: "LOW" };
  const priority = { id: "priority-1", rank: 1, title: "Improve reconciliation", description: "Address the payroll reconciliation risk.", dimension: "OPERATIONS", addressedWeaknesses: [], leveragedStrengths: [], urgency: "IMMEDIATE" };
  const recommendation = { id: "recommendation-1", priorityId: "priority-1", proposedAction: "Introduce automated reconciliation checks.", expectedOutcome: "Earlier detection of payroll discrepancies.", effortEstimate: "LOW", evidenceRefs: ["risk-1", "opportunity-1"] };
  const narrative = { executiveSummary: "Established controls support targeted payroll automation.", currentState: "Controls are established.", burningIssues: "Reconciliation delays.", opportunitiesForGrowth: "Automated checks." };
  const summary = { headline: "Target payroll automation", keyInsights: ["Controls provide a foundation."], criticalRisksSummary: "Reconciliation delays." };
  const reasoningReport = { reportId: "report-1", timestamp: T, overallStatus: "SUPPORTED_FINDING", findings: [finding], risks: [risk], opportunities: [opportunity], rootCauses: [], rejectedClaims: [], readinessGaps: [] };
  const dossier = { dossierId: "dossier-1", reportRef: "report-1", timestamp: T, diagnosticStatus: "VALID", blocks: [], executiveSummary: summary, businessDiagnosis: { overallMaturity: "MANAGED", dimensionAssessments: [{ dimension: "OPERATIONS", level: "MANAGED", score: 68, evidenceRefs: ["finding-1"], justification: "Established scheduling controls." }], strengths: [], weaknesses: [] }, priorities: [priority], recommendationCandidates: [recommendation], narrative, diagnosticAudit: { rejectedClaims: [] } };
  const assessment = { assessmentId: "assessment-1", dossierRef: "dossier-1", reasoningReportRef: "report-1", executionId: "execution-1", status: "COMPLETE", maturityProfile: { overallMaturity: "MANAGED", dimensions: [{ dimension: "OPERATIONS", maturity: "MANAGED", score: 68, strengths: [], weaknesses: [] }] }, findings: [finding], risks: [risk], opportunities: [opportunity], rootCauses: [], transformationPriorities: [{ ...priority, readinessDependencyIds: [] }], recommendationCandidates: [recommendation], transformationReadiness: { status: "READY", score: 80, criticalGaps: [], constraints: [], dependencies: [] }, confidenceMatrix: { overallConfidence: 0.8, support: 0.8, directness: 0.8, consistency: 0.8, coverage: 0.8, causalConfidence: 0.8, dimensionConfidence: { OPERATIONS: 0.8 } }, evidenceMap: { mapId: "map-1", links: [] }, executiveInsight: { summary, narrative, keyTakeaways: [{ text: finding.statement, sourceRefs: ["finding-1"] }] }, audit: { rejectedClaims: [], diagnosticAudit: { rejectedClaims: [] }, limitations: [], invalidReferences: [], unresolvedContradictions: [], insufficientEvidenceRefs: [] }, metadata: { version: "1", schema: "1", generator: "EnterpriseTransformationAssessmentBuilder", policyVersion: "1", timestamp: T } };
  return { executionId: "execution-1", sessionId, status: "SUCCEEDED", stageResults: { TRANSFORMATION_ASSESSMENT: { stage: "TRANSFORMATION_ASSESSMENT", status: "SUCCEEDED", startedAt: T, completedAt: T, durationMs: 0, errors: [], warnings: [], output: { sessionId, reasoningReport, dossier, assessment } } }, errors: [], warnings: [], rawData: { secret: "RAW_SECRET", authority: "INTERNAL_AUTHORITY", policy: "INTERNAL_POLICY" } };
}
function harness() {
  const verifier = { verify: vi.fn<OidcServiceIdentityVerifierV1["verify"]>().mockResolvedValue({ subject: { schemaVersion: "1", subjectType: "SERVICE", provider: "GOOGLE_CLOUD_IAM", providerSubjectId: "google-oidc-sub:123", authenticationMethod: "OIDC_SERVICE_ACCOUNT", authenticatedAt: EARLIER, tokenIssuedAt: EARLIER, tokenExpiresAt: "2026-07-28T13:00:00.000Z", revocationCheckedAt: T, credentialVersion: "1" }, verifiedGoogleSubject: "123", serviceAccountEmail: DISCOVERY_OIDC_EXPECTED_SERVICE_ACCOUNT_EMAIL_V1 }) };
  const authorityResolver = { resolveAuthority: vi.fn<FirestoreOidcServiceIdentityBindingResolverV1["resolveAuthority"]>().mockResolvedValue({ binding: { schemaVersion: "1", bindingVersion: "1", principalType: "SERVICE", provider: "GOOGLE_CLOUD_IAM", providerSubjectId: "google-oidc-sub:123", canonicalPrincipalId: "service-canonical", bindingId: "binding-1", status: "ACTIVE", verifiedAt: EARLIER, resolverVersion: "resolver-v1" }, tenant: { schemaVersion: "1", tenantId: "tenant-canonical", status: "ACTIVE", authorityVersion: "1", resolvedAt: T, tenantRecordVersion: "1" }, membership: { schemaVersion: "1", membershipId: "membership-1", principalType: "SERVICE", principalId: "service-canonical", tenantId: "tenant-canonical", roles: ["TENANT_SERVICE"], status: "ACTIVE", membershipVersion: "1", createdAt: EARLIER, updatedAt: EARLIER, authorityVersion: "1" }, resolvedAt: T }) };
  let sequence = 0;
  const execute = vi.fn<NonNullable<Parameters<typeof createExecutiveDiscoveryReceiverCompositionV1>[0]["executionAdapter"]>["execute"]>().mockImplementation(async input => { controls.dispatches++; return output(input.sessionId); });
  const composition = createExecutiveDiscoveryReceiverCompositionV1({ firestore: {} as Firestore, verifier, authorityResolver, executionAdapter: { execute }, now: () => T, generateId: () => ++sequence === 1 ? "trusted-request" : "trusted-correlation" });
  const handler = createExecutiveDiscoveryHttpHandlerV1(() => composition);
  const http = (body: unknown = request()) => ({ method: "POST", headers: { "content-type": "application/json; charset=utf-8", authorization: "Bearer TOKEN_SECRET" }, rawBody: Buffer.from(JSON.stringify(body)) });
  return { composition, handler, http, execute, verifier, authorityResolver };
}
beforeEach(() => { controls.policy = "ALLOW"; controls.dispatches = 0; controls.queries = []; });
afterEach(() => { vi.restoreAllMocks(); });
describe("Executive Discovery receiver", () => {
  it("rejects non-POST before authentication", async () => { const h = harness(); expect((await h.handler({ ...h.http(), method: "GET" })).status).toBe(405); expect(h.verifier.verify).not.toHaveBeenCalled(); });
  it("requires JSON", async () => { const h = harness(); expect((await h.handler({ ...h.http(), headers: { "content-type": "text/plain" } })).status).toBe(415); });
  it("bounds the raw body before parsing", async () => { const h = harness(); expect((await h.handler({ ...h.http(), rawBody: Buffer.alloc(EXECUTIVE_DISCOVERY_MAX_BODY_BYTES_V1 + 1) })).status).toBe(413); expect(h.execute).not.toHaveBeenCalled(); });
  it("rejects malformed JSON", async () => { const h = harness(); expect((await h.handler({ ...h.http(), rawBody: Buffer.from("{") })).status).toBe(400); });
  it.each([[false, true], [true, false], [false, false]])("rejects privacyConsent=%s and diagnosticProcessingConsent=%s before execution", async (privacyConsent, diagnosticProcessingConsent) => { const h = harness(); const body = request(); const denied = { ...body, consentAssertion: { ...body.consentAssertion, privacyConsent, diagnosticProcessingConsent } }; await expect(h.composition.evaluate("Bearer TOKEN_SECRET", denied)).rejects.toMatchObject({ status: 400, safeCode: "INVALID_REQUEST", message: "INVALID_REQUEST" }); const result = await h.handler(h.http(denied)); expect(result).toEqual({ status: 400, body: { success: false, error: { code: "INVALID_REQUEST", message: "Executive Discovery request could not be completed." } } }); expect(h.verifier.verify).not.toHaveBeenCalled(); expect(h.authorityResolver.resolveAuthority).not.toHaveBeenCalled(); expect(controls.queries).toHaveLength(0); expect(h.execute).not.toHaveBeenCalled(); });
  it("rejects otherwise-valid consumed evidence outside executive-diagnosis consent before execution", async () => { const h = harness(); const body = request(); const denied = { ...body, evidence: body.evidence.map(item => ({ ...item, consentScope: "marketing" })) }; await expect(h.composition.evaluate("Bearer TOKEN_SECRET", denied)).rejects.toMatchObject({ status: 400, safeCode: "INVALID_REQUEST", message: "INVALID_REQUEST" }); const result = await h.handler(h.http(denied)); expect(result).toEqual({ status: 400, body: { success: false, error: { code: "INVALID_REQUEST", message: "Executive Discovery request could not be completed." } } }); expect(h.verifier.verify).not.toHaveBeenCalled(); expect(h.authorityResolver.resolveAuthority).not.toHaveBeenCalled(); expect(controls.queries).toHaveLength(0); expect(h.execute).not.toHaveBeenCalled(); expect(JSON.stringify(result)).not.toMatch(/receipt-1|HOSPITALITY|TOKEN_SECRET|stack|INTERNAL_AUTHORITY|INTERNAL_POLICY/); });
  it("allows executive diagnosis when marketingConsent is false", async () => { const h = harness(); const body = request(); const allowed = { ...body, consentAssertion: { ...body.consentAssertion, marketingConsent: false } }; const result = await h.handler(h.http(allowed)); expect(result.status).toBe(200); expect(result.body.success).toBe(true); if (result.body.success) expect(isExecutiveDiagnosisForRequest(result.body.data, allowed)).toBe(true); expect(h.execute).toHaveBeenCalledTimes(1); expect(controls.queries).toHaveLength(1); });
  it.each([undefined, "", "Basic secret", "Bearer a b", ["Bearer a", "Bearer b"]])("rejects missing or invalid Authorization %s", async authorization => { const h = harness(); expect((await h.handler({ ...h.http(), headers: { ...h.http().headers, authorization } })).status).toBe(401); expect(h.verifier.verify).not.toHaveBeenCalled(); });
  it("uses the exact receiver-owned OIDC audience", async () => { const h = harness(); expect((await h.handler(h.http())).status).toBe(200); expect(h.verifier.verify).toHaveBeenCalledWith({ authorizationHeader: "Bearer TOKEN_SECRET", expectedAudience: EXECUTIVE_DISCOVERY_RECEIVER_AUDIENCE_V1, verifiedAt: T }); });
  it("fails closed on verifier failure without exposing its error", async () => { const h = harness(); h.verifier.verify.mockRejectedValue(new Error("Bearer TOKEN_SECRET stack INTERNAL_AUTHORITY")); const result = await h.handler(h.http()); expect(result.status).toBe(401); expect(JSON.stringify(result)).not.toMatch(/TOKEN_SECRET|stack|INTERNAL_AUTHORITY/); expect(h.authorityResolver.resolveAuthority).not.toHaveBeenCalled(); });
  it("rejects a cryptographically verified token for a different audience", async () => { const client = new OAuth2Client(); vi.spyOn(client, "verifyIdToken").mockImplementation(async () => new LoginTicket("header", { iss: "https://accounts.google.com", sub: "123", aud: `${EXECUTIVE_DISCOVERY_RECEIVER_AUDIENCE_V1}/other`, email: DISCOVERY_OIDC_EXPECTED_SERVICE_ACCOUNT_EMAIL_V1, email_verified: true, iat: Date.parse(EARLIER) / 1000, exp: Date.parse("2026-07-28T13:00:00.000Z") / 1000 })); await expect(new OidcServiceIdentityVerifierV1(client).verify({ authorizationHeader: "Bearer token", expectedAudience: EXECUTIVE_DISCOVERY_RECEIVER_AUDIENCE_V1, verifiedAt: T })).rejects.toMatchObject({ code: "TOKEN_AUDIENCE_MISMATCH" }); });
  it("fails closed on authority resolution failure", async () => { const h = harness(); h.authorityResolver.resolveAuthority.mockRejectedValue(new Error("PRIVATE_BINDING")); expect((await h.handler(h.http())).status).toBe(403); expect(h.execute).not.toHaveBeenCalled(); });
  it("binds policy and execution to canonical authority, never body identifiers", async () => { const h = harness(); const result = await h.handler(h.http()); expect(result.status).toBe(200); expect(controls.queries).toEqual([{ schemaVersion: "1", tenantId: "tenant-canonical", consumerId: "AURA_DISCOVERY", source: "AURA_DISCOVERY", requestedMode: "SHADOW_ONLY", actor: { actorType: "SERVICE", actorId: "service-canonical" } }]); expect(h.execute.mock.calls[0][0]).toMatchObject({ sessionId: "trusted-correlation", authoritativeContext: { tenantId: "tenant-canonical", actor: { actorType: "SERVICE", actorId: "service-canonical" }, requestId: "trusted-request", correlationId: "trusted-correlation", executionMode: "SHADOW_ONLY" } }); expect(JSON.stringify(h.execute.mock.calls[0][0].payload)).not.toMatch(/untrusted-business-tenant|business-request|business-company/); });
  it("accepts discovery provenance with a narrow field fragment through the governed boundary", async () => { const h = harness(); expect((await h.handler(h.http())).status).toBe(200); expect(h.execute.mock.calls[0][0].payload).toMatchObject({ facts: [{ provenance: { sourceId: "discovery_sessions/business-session#dossier.industry" } }] }); });
  it("rejects unrelated provenance fragments", async () => { const h = harness(); const body = request(); expect((await h.handler(h.http({ ...body, evidence: body.evidence.map(item => ({ ...item, sourceReference: "unrelated#field" })) }))).status).toBe(400); });
  it("denies execution at the real governed boundary when policy denies", async () => { controls.policy = "DENY"; const h = harness(); expect((await h.handler(h.http())).status).toBe(403); expect(controls.queries).toHaveLength(1); expect(h.execute).not.toHaveBeenCalled(); });
  it("rejects policy escalation at the real governed boundary", async () => { controls.policy = "ESCALATE"; const h = harness(); expect((await h.handler(h.http())).status).toBe(403); expect(h.execute).not.toHaveBeenCalled(); });
  it.each(["PRODUCTIVE", "EVALUATION"])("rejects caller mode %s", async mode => { const h = harness(); expect((await h.handler(h.http({ ...request(), metadata: { evaluationMode: mode } }))).status).toBe(400); expect((await h.handler(h.http({ ...request(), requestedMode: mode }))).status).toBe(400); expect(h.execute).not.toHaveBeenCalled(); });
  it("does not leak raw output, authority, policy, or bearer credentials", async () => { const h = harness(); const result = await h.handler(h.http()); expect(result.status).toBe(200); expect(JSON.stringify(result)).not.toMatch(/RAW_SECRET|INTERNAL_AUTHORITY|INTERNAL_POLICY|TOKEN_SECRET|authoritativeContext|authorizationPolicyVersion|stageResults|rawData/); });
  it("returns a safe failure for malformed executive output", async () => { const h = harness(); h.execute.mockResolvedValue({ executionId: "execution-1", sessionId: "trusted-correlation", status: "SUCCEEDED", stageResults: {} }); const result = await h.handler(h.http()); expect(result.status).toBe(502); expect(result.body).toEqual({ success: false, error: { code: "INVALID_EXECUTIVE_OUTPUT", message: "Executive Discovery request could not be completed." } }); });
  it("keeps simultaneous captures separate", async () => { const left = harness(); const right = harness(); const results = await Promise.all([left.handler(left.http()), right.handler(right.http())]); expect(results.map(result => result.status)).toEqual([200, 200]); expect(controls.dispatches).toBe(2); });
});
describe("Real executive output projection", () => {
  const project = () => mapInternalExecutionResultToExecutiveDiagnosisV1(output(), request(), "trusted-correlation");
  it("produces a contract-valid diagnosis", () => { expect(isExecutiveDiagnosisForRequest(project(), request())).toBe(true); });
  it("derives non-placeholder maturity from the assessment", () => { expect(project().maturity).toMatchObject({ overallScore: 68, level: "STRUCTURED", dimensions: [{ score: 68, rationale: "Established scheduling controls." }] }); });
  it("projects a real risk", () => { expect(project().risks[0]).toMatchObject({ riskId: "risk-1", description: "Manual reconciliation can delay payroll.", severity: "HIGH", evidenceIds: ["legacy-dossier.industry"] }); });
  it("projects a real opportunity", () => { expect(project().opportunities[0]).toMatchObject({ opportunityId: "opportunity-1", expectedValue: "Reduce reconciliation delays.", feasibility: 0.8, horizon: "NEAR_TERM" }); });
  it("projects a real recommendation", () => { expect(project().recommendations[0]).toMatchObject({ recommendationId: "recommendation-1", description: "Introduce automated reconciliation checks.", expectedImpact: "Earlier detection of payroll discrepancies." }); });
  it("projects the real executive summary", () => { expect(project().executiveSummary).toBe("Established controls support targeted payroll automation."); });
  it("retains reasoning risks when assessment risks are empty", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment.risks = []; expect(mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation").risks).toHaveLength(1); });
  it("rejects an empty maturity profile", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment.maturityProfile.dimensions = []; expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow("EXECUTIVE_OUTPUT_INVALID"); });
  it("rejects malformed domain values", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment.confidenceMatrix.overallConfidence = NaN; expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); });
  it("rejects cross-execution output", () => { expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(output("other-session"), request(), "trusted-correlation")).toThrow(); });
  it("rejects cross-dossier references", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment.dossierRef = "other-dossier"; expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); });
  it("rejects inaccessible evidence references instead of inventing support", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.output.reasoningReport.findings[0].chain.claims[0].evidenceSupports[0].evidenceRef = "unknown-evidence"; expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); });
  it("rejects accessors without evaluating them", () => { const result = output(); const getter = vi.fn(() => "SECRET"); Object.defineProperty(result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment, "status", { enumerable: true, get: getter }); expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); expect(getter).not.toHaveBeenCalled(); });
  it("never reads rawData", () => { const result = output(); const getter = vi.fn(() => { throw new Error("RAW_SECRET"); }); Object.defineProperty(result, "rawData", { enumerable: true, get: getter }); expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); expect(getter).not.toHaveBeenCalled(); });
  it("rejects additional executive fields", () => { const result = output(); Object.assign(result.stageResults.TRANSFORMATION_ASSESSMENT.output.assessment, { internalAuthority: "SECRET" }); expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); });
  it("requires successful transformation output even when rawData contains a result", () => { const result = output(); result.stageResults.TRANSFORMATION_ASSESSMENT.status = "FAILED"; expect(() => mapInternalExecutionResultToExecutiveDiagnosisV1(result, request(), "trusted-correlation")).toThrow(); });
  it("projects domain findings without copying raw business evidence", () => { const body = request(); const diagnosis = mapInternalExecutionResultToExecutiveDiagnosisV1(output(), { ...body, evidence: body.evidence.map(item => ({ ...item, value: "RAW_BUSINESS_SECRET" })) }, "trusted-correlation"); expect(diagnosis.businessSnapshot.inferredFacts[0].value).toBe("Scheduling controls are established."); expect(JSON.stringify(diagnosis)).not.toContain("RAW_BUSINESS_SECRET"); });
});
