export const FIRESTORE_DISCOVERY_INTAKE_IDEMPOTENCY_COLLECTION =
  "discovery_intake_idempotency";

export const FIRESTORE_DISCOVERY_INTAKE_IDEMPOTENCY_NAMESPACE_COLLECTION =
  "discovery_intake_idempotency_namespaces_v1";

export const FIRESTORE_DISCOVERY_INTAKE_IDEMPOTENCY_NAMESPACE_VERSION =
  "DISCOVERY_INTAKE_IDEMPOTENCY_NAMESPACE_V1" as const;
